# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelecineDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TelecineDialog(object):
    def setupUi(self, TelecineDialog):
        TelecineDialog.setObjectName("TelecineDialog")
        TelecineDialog.resize(676, 1056)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TelecineDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(TelecineDialog)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 652, 1029))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.initGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.initGroupBox.setGeometry(QtCore.QRect(10, 10, 631, 161))
        self.initGroupBox.setStyleSheet("QGroupBox#initGroupBox { \n"
"     border: 1px solid black; \n"
" } ")
        self.initGroupBox.setObjectName("initGroupBox")
        self.cameraGroupBox = QtWidgets.QGroupBox(self.initGroupBox)
        self.cameraGroupBox.setGeometry(QtCore.QRect(140, 10, 391, 141))
        self.cameraGroupBox.setObjectName("cameraGroupBox")
        self.label_16 = QtWidgets.QLabel(self.cameraGroupBox)
        self.label_16.setGeometry(QtCore.QRect(120, 20, 47, 21))
        self.label_16.setObjectName("label_16")
        self.modeBox = QtWidgets.QSpinBox(self.cameraGroupBox)
        self.modeBox.setGeometry(QtCore.QRect(160, 20, 42, 22))
        self.modeBox.setMinimum(0)
        self.modeBox.setMaximum(7)
        self.modeBox.setProperty("value", 2)
        self.modeBox.setObjectName("modeBox")
        self.cameraVersionLabel = QtWidgets.QLabel(self.cameraGroupBox)
        self.cameraVersionLabel.setGeometry(QtCore.QRect(220, 20, 81, 21))
        self.cameraVersionLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraVersionLabel.setText("")
        self.cameraVersionLabel.setObjectName("cameraVersionLabel")
        self.hresLineEdit = QtWidgets.QLineEdit(self.cameraGroupBox)
        self.hresLineEdit.setGeometry(QtCore.QRect(160, 50, 51, 20))
        self.hresLineEdit.setObjectName("hresLineEdit")
        self.vresLineEdit = QtWidgets.QLineEdit(self.cameraGroupBox)
        self.vresLineEdit.setGeometry(QtCore.QRect(160, 80, 51, 20))
        self.vresLineEdit.setObjectName("vresLineEdit")
        self.label_9 = QtWidgets.QLabel(self.cameraGroupBox)
        self.label_9.setGeometry(QtCore.QRect(120, 50, 47, 21))
        self.label_9.setObjectName("label_9")
        self.openCameraButton = QtWidgets.QPushButton(self.cameraGroupBox)
        self.openCameraButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.openCameraButton.setObjectName("openCameraButton")
        self.closeCameraButton = QtWidgets.QPushButton(self.cameraGroupBox)
        self.closeCameraButton.setGeometry(QtCore.QRect(310, 20, 75, 23))
        self.closeCameraButton.setObjectName("closeCameraButton")
        self.hflipCheckBox = QtWidgets.QCheckBox(self.cameraGroupBox)
        self.hflipCheckBox.setGeometry(QtCore.QRect(320, 50, 41, 17))
        self.hflipCheckBox.setObjectName("hflipCheckBox")
        self.vflipCheckBox = QtWidgets.QCheckBox(self.cameraGroupBox)
        self.vflipCheckBox.setGeometry(QtCore.QRect(320, 80, 41, 17))
        self.vflipCheckBox.setObjectName("vflipCheckBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.cameraGroupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 50, 101, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.calibrateNoneButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.calibrateNoneButton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.calibrateNoneButton.setChecked(True)
        self.calibrateNoneButton.setObjectName("calibrateNoneButton")
        self.calibrateFlatButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.calibrateFlatButton.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.calibrateFlatButton.setObjectName("calibrateFlatButton")
        self.calibrateTableButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.calibrateTableButton.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.calibrateTableButton.setObjectName("calibrateTableButton")
        self.label_22 = QtWidgets.QLabel(self.cameraGroupBox)
        self.label_22.setGeometry(QtCore.QRect(120, 80, 31, 21))
        self.label_22.setObjectName("label_22")
        self.groupBox = QtWidgets.QGroupBox(self.initGroupBox)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 121, 141))
        self.groupBox.setObjectName("groupBox")
        self.connectButton = QtWidgets.QPushButton(self.groupBox)
        self.connectButton.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.connectButton.setObjectName("connectButton")
        self.ipLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ipLineEdit.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.motorOnGroupBox = QtWidgets.QGroupBox(self.initGroupBox)
        self.motorOnGroupBox.setGeometry(QtCore.QRect(540, 10, 81, 141))
        self.motorOnGroupBox.setObjectName("motorOnGroupBox")
        self.motorOnButton = QtWidgets.QPushButton(self.motorOnGroupBox)
        self.motorOnButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.motorOnButton.setObjectName("motorOnButton")
        self.motorOffButton = QtWidgets.QPushButton(self.motorOnGroupBox)
        self.motorOffButton.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.motorOffButton.setObjectName("motorOffButton")
        self.motorControlGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.motorControlGroupBox.setGeometry(QtCore.QRect(10, 180, 631, 51))
        self.motorControlGroupBox.setStyleSheet("QGroupBox#motorControlGroupBox { \n"
"     border: 1px solid black; \n"
" } ")
        self.motorControlGroupBox.setObjectName("motorControlGroupBox")
        self.forwardButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.forwardButton.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.forwardButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.forwardButton.setObjectName("forwardButton")
        self.backwardButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.backwardButton.setGeometry(QtCore.QRect(80, 20, 61, 21))
        self.backwardButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.backwardButton.setObjectName("backwardButton")
        self.motorStopButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.motorStopButton.setGeometry(QtCore.QRect(150, 20, 61, 21))
        self.motorStopButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.motorStopButton.setObjectName("motorStopButton")
        self.forwardOneButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.forwardOneButton.setGeometry(QtCore.QRect(220, 20, 61, 21))
        self.forwardOneButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.forwardOneButton.setObjectName("forwardOneButton")
        self.backwardOneButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.backwardOneButton.setGeometry(QtCore.QRect(290, 20, 61, 21))
        self.backwardOneButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.backwardOneButton.setObjectName("backwardOneButton")
        self.label_17 = QtWidgets.QLabel(self.motorControlGroupBox)
        self.label_17.setGeometry(QtCore.QRect(510, 20, 47, 16))
        self.label_17.setObjectName("label_17")
        self.motorSpeedBox = QtWidgets.QDoubleSpinBox(self.motorControlGroupBox)
        self.motorSpeedBox.setGeometry(QtCore.QRect(550, 20, 41, 22))
        self.motorSpeedBox.setDecimals(1)
        self.motorSpeedBox.setMinimum(0.0)
        self.motorSpeedBox.setMaximum(10.0)
        self.motorSpeedBox.setSingleStep(0.1)
        self.motorSpeedBox.setProperty("value", 5.0)
        self.motorSpeedBox.setObjectName("motorSpeedBox")
        self.motorOnTriggerButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.motorOnTriggerButton.setGeometry(QtCore.QRect(360, 20, 61, 21))
        self.motorOnTriggerButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.motorOnTriggerButton.setObjectName("motorOnTriggerButton")
        self.motorCalibrateButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.motorCalibrateButton.setGeometry(QtCore.QRect(430, 20, 61, 21))
        self.motorCalibrateButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.motorCalibrateButton.setObjectName("motorCalibrateButton")
        self.cameraControlGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.cameraControlGroupBox.setGeometry(QtCore.QRect(10, 240, 631, 261))
        self.cameraControlGroupBox.setStyleSheet("QGroupBox#cameraControlGroupBox { \n"
"     border: 0.5px solid black; \n"
" } ")
        self.cameraControlGroupBox.setObjectName("cameraControlGroupBox")
        self.takeImageButton = QtWidgets.QPushButton(self.cameraControlGroupBox)
        self.takeImageButton.setGeometry(QtCore.QRect(20, 20, 61, 23))
        self.takeImageButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.takeImageButton.setObjectName("takeImageButton")
        self.captureStopButton = QtWidgets.QPushButton(self.cameraControlGroupBox)
        self.captureStopButton.setGeometry(QtCore.QRect(190, 20, 61, 23))
        self.captureStopButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.captureStopButton.setObjectName("captureStopButton")
        self.captureStartButton = QtWidgets.QPushButton(self.cameraControlGroupBox)
        self.captureStartButton.setGeometry(QtCore.QRect(110, 20, 61, 23))
        self.captureStartButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.captureStartButton.setObjectName("captureStartButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.cameraControlGroupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 50, 601, 201))
        self.groupBox_5.setObjectName("groupBox_5")
        self.playButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.playButton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.playButton.setChecked(True)
        self.playButton.setObjectName("playButton")
        self.onFrameButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.onFrameButton.setGeometry(QtCore.QRect(80, 20, 67, 17))
        self.onFrameButton.setChecked(False)
        self.onFrameButton.setObjectName("onFrameButton")
        self.onTriggerButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.onTriggerButton.setGeometry(QtCore.QRect(160, 20, 71, 17))
        self.onTriggerButton.setObjectName("onTriggerButton")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(10, 50, 50, 16))
        self.label_31.setObjectName("label_31")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(10, 80, 60, 16))
        self.label_29.setObjectName("label_29")
        self.captureMotorSpeedBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.captureMotorSpeedBox.setGeometry(QtCore.QRect(90, 80, 51, 22))
        self.captureMotorSpeedBox.setDecimals(1)
        self.captureMotorSpeedBox.setMinimum(0.0)
        self.captureMotorSpeedBox.setMaximum(10.0)
        self.captureMotorSpeedBox.setSingleStep(0.1)
        self.captureMotorSpeedBox.setProperty("value", 5.0)
        self.captureMotorSpeedBox.setObjectName("captureMotorSpeedBox")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(430, 50, 61, 16))
        self.label_24.setObjectName("label_24")
        self.shutterAutoWaitBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.shutterAutoWaitBox.setGeometry(QtCore.QRect(510, 50, 37, 20))
        self.shutterAutoWaitBox.setMaximum(20)
        self.shutterAutoWaitBox.setSingleStep(1)
        self.shutterAutoWaitBox.setProperty("value", 8)
        self.shutterAutoWaitBox.setObjectName("shutterAutoWaitBox")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(550, 50, 33, 16))
        self.label_34.setObjectName("label_34")
        self.bracketCheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.bracketCheckBox.setGeometry(QtCore.QRect(300, 20, 70, 17))
        self.bracketCheckBox.setObjectName("bracketCheckBox")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(300, 50, 47, 21))
        self.label_12.setObjectName("label_12")
        self.darkCoefficientBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.darkCoefficientBox.setGeometry(QtCore.QRect(360, 50, 62, 22))
        self.darkCoefficientBox.setMinimum(0.0)
        self.darkCoefficientBox.setMaximum(2.0)
        self.darkCoefficientBox.setSingleStep(0.1)
        self.darkCoefficientBox.setProperty("value", 0.1)
        self.darkCoefficientBox.setObjectName("darkCoefficientBox")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(300, 80, 47, 21))
        self.label_21.setObjectName("label_21")
        self.lightCoefficientBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.lightCoefficientBox.setGeometry(QtCore.QRect(360, 80, 62, 22))
        self.lightCoefficientBox.setMinimum(0.1)
        self.lightCoefficientBox.setMaximum(10.0)
        self.lightCoefficientBox.setSingleStep(0.1)
        self.lightCoefficientBox.setProperty("value", 2.0)
        self.lightCoefficientBox.setObjectName("lightCoefficientBox")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(430, 80, 71, 16))
        self.label_23.setObjectName("label_23")
        self.shutterSpeedWaitBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.shutterSpeedWaitBox.setGeometry(QtCore.QRect(510, 80, 37, 20))
        self.shutterSpeedWaitBox.setMaximum(10)
        self.shutterSpeedWaitBox.setSingleStep(1)
        self.shutterSpeedWaitBox.setProperty("value", 4)
        self.shutterSpeedWaitBox.setObjectName("shutterSpeedWaitBox")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(550, 80, 33, 16))
        self.label_26.setObjectName("label_26")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 381, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.resetROIButton = QtWidgets.QPushButton(self.groupBox_2)
        self.resetROIButton.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.resetROIButton.setObjectName("resetROIButton")
        self.ROIxBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ROIxBox.setGeometry(QtCore.QRect(41, 20, 62, 22))
        self.ROIxBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROIxBox.setDecimals(0)
        self.ROIxBox.setMinimum(0.0)
        self.ROIxBox.setMaximum(50000.0)
        self.ROIxBox.setSingleStep(1.0)
        self.ROIxBox.setProperty("value", 0.0)
        self.ROIxBox.setObjectName("ROIxBox")
        self.setROIButton = QtWidgets.QPushButton(self.groupBox_2)
        self.setROIButton.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.setROIButton.setObjectName("setROIButton")
        self.ROIhBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ROIhBox.setGeometry(QtCore.QRect(131, 50, 62, 22))
        self.ROIhBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROIhBox.setDecimals(0)
        self.ROIhBox.setMinimum(0.0)
        self.ROIhBox.setMaximum(50000.0)
        self.ROIhBox.setSingleStep(1.0)
        self.ROIhBox.setProperty("value", 0.0)
        self.ROIhBox.setObjectName("ROIhBox")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(11, 20, 81, 20))
        self.label_30.setObjectName("label_30")
        self.ROIyBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ROIyBox.setGeometry(QtCore.QRect(131, 20, 62, 22))
        self.ROIyBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROIyBox.setDecimals(0)
        self.ROIyBox.setMinimum(0.0)
        self.ROIyBox.setMaximum(50000.0)
        self.ROIyBox.setSingleStep(1.0)
        self.ROIyBox.setProperty("value", 0.0)
        self.ROIyBox.setObjectName("ROIyBox")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(121, 20, 51, 20))
        self.label_36.setObjectName("label_36")
        self.keepRatioCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.keepRatioCheckBox.setGeometry(QtCore.QRect(201, 20, 101, 17))
        self.keepRatioCheckBox.setObjectName("keepRatioCheckBox")
        self.centerCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.centerCheckBox.setGeometry(QtCore.QRect(201, 50, 51, 17))
        self.centerCheckBox.setObjectName("centerCheckBox")
        self.ROIwBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ROIwBox.setGeometry(QtCore.QRect(41, 50, 62, 22))
        self.ROIwBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROIwBox.setDecimals(0)
        self.ROIwBox.setMinimum(0.0)
        self.ROIwBox.setMaximum(50000.0)
        self.ROIwBox.setSingleStep(1.0)
        self.ROIwBox.setProperty("value", 0.0)
        self.ROIwBox.setObjectName("ROIwBox")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(120, 50, 31, 20))
        self.label_38.setObjectName("label_38")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setGeometry(QtCore.QRect(410, 110, 171, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.resizeCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.resizeCheckBox.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.resizeCheckBox.setObjectName("resizeCheckBox")
        self.resizewBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.resizewBox.setGeometry(QtCore.QRect(90, 20, 62, 22))
        self.resizewBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resizewBox.setDecimals(0)
        self.resizewBox.setMinimum(0.0)
        self.resizewBox.setMaximum(50000.0)
        self.resizewBox.setSingleStep(1.0)
        self.resizewBox.setProperty("value", 0.0)
        self.resizewBox.setObjectName("resizewBox")
        self.resizehBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.resizehBox.setGeometry(QtCore.QRect(90, 50, 62, 22))
        self.resizehBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resizehBox.setDecimals(0)
        self.resizehBox.setMinimum(0.0)
        self.resizehBox.setMaximum(50000.0)
        self.resizehBox.setSingleStep(1.0)
        self.resizehBox.setProperty("value", 0.0)
        self.resizehBox.setObjectName("resizehBox")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(70, 20, 31, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(70, 50, 31, 16))
        self.label_40.setObjectName("label_40")
        self.maxFpsButton = QtWidgets.QPushButton(self.groupBox_5)
        self.maxFpsButton.setGeometry(QtCore.QRect(170, 50, 61, 23))
        self.maxFpsButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.maxFpsButton.setObjectName("maxFpsButton")
        self.framerateBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.framerateBox.setGeometry(QtCore.QRect(90, 50, 51, 22))
        self.framerateBox.setDecimals(1)
        self.framerateBox.setMinimum(0.0)
        self.framerateBox.setMaximum(50.0)
        self.framerateBox.setSingleStep(0.1)
        self.framerateBox.setProperty("value", 30.0)
        self.framerateBox.setObjectName("framerateBox")
        self.maxSpeedButton = QtWidgets.QPushButton(self.groupBox_5)
        self.maxSpeedButton.setGeometry(QtCore.QRect(170, 80, 61, 23))
        self.maxSpeedButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.maxSpeedButton.setObjectName("maxSpeedButton")
        self.capturePauseButton = QtWidgets.QPushButton(self.cameraControlGroupBox)
        self.capturePauseButton.setGeometry(QtCore.QRect(260, 20, 61, 23))
        self.capturePauseButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.capturePauseButton.setObjectName("capturePauseButton")
        self.autoPauseCheckBox = QtWidgets.QCheckBox(self.cameraControlGroupBox)
        self.autoPauseCheckBox.setGeometry(QtCore.QRect(400, 10, 81, 20))
        self.autoPauseCheckBox.setObjectName("autoPauseCheckBox")
        self.label_33 = QtWidgets.QLabel(self.cameraControlGroupBox)
        self.label_33.setGeometry(QtCore.QRect(500, 10, 47, 13))
        self.label_33.setObjectName("label_33")
        self.pauseEdit = QtWidgets.QLineEdit(self.cameraControlGroupBox)
        self.pauseEdit.setGeometry(QtCore.QRect(530, 10, 31, 16))
        self.pauseEdit.setObjectName("pauseEdit")
        self.pauseLevelCheckBox = QtWidgets.QCheckBox(self.cameraControlGroupBox)
        self.pauseLevelCheckBox.setGeometry(QtCore.QRect(530, 30, 41, 17))
        self.pauseLevelCheckBox.setObjectName("pauseLevelCheckBox")
        self.frameProcessingGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.frameProcessingGroupBox.setGeometry(QtCore.QRect(10, 510, 631, 111))
        self.frameProcessingGroupBox.setStyleSheet("QGroupBox#frameProcessingGroupBox { \n"
"     border: 1px solid black; \n"
" } ")
        self.frameProcessingGroupBox.setObjectName("frameProcessingGroupBox")
        self.saveCheckBox = QtWidgets.QCheckBox(self.frameProcessingGroupBox)
        self.saveCheckBox.setGeometry(QtCore.QRect(10, 80, 61, 20))
        self.saveCheckBox.setObjectName("saveCheckBox")
        self.chooseDirectoryButton = QtWidgets.QPushButton(self.frameProcessingGroupBox)
        self.chooseDirectoryButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.chooseDirectoryButton.setObjectName("chooseDirectoryButton")
        self.tapeBox = QtWidgets.QSpinBox(self.frameProcessingGroupBox)
        self.tapeBox.setGeometry(QtCore.QRect(110, 20, 51, 22))
        self.tapeBox.setMaximum(99)
        self.tapeBox.setSingleStep(1)
        self.tapeBox.setProperty("value", 1)
        self.tapeBox.setObjectName("tapeBox")
        self.label_27 = QtWidgets.QLabel(self.frameProcessingGroupBox)
        self.label_27.setGeometry(QtCore.QRect(80, 20, 47, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frameProcessingGroupBox)
        self.label_28.setGeometry(QtCore.QRect(170, 20, 41, 20))
        self.label_28.setObjectName("label_28")
        self.clipBox = QtWidgets.QSpinBox(self.frameProcessingGroupBox)
        self.clipBox.setGeometry(QtCore.QRect(190, 20, 51, 22))
        self.clipBox.setMaximum(99)
        self.clipBox.setSingleStep(1)
        self.clipBox.setProperty("value", 1)
        self.clipBox.setObjectName("clipBox")
        self.directoryDisplay = QtWidgets.QLabel(self.frameProcessingGroupBox)
        self.directoryDisplay.setGeometry(QtCore.QRect(10, 50, 311, 21))
        self.directoryDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.directoryDisplay.setText("")
        self.directoryDisplay.setObjectName("directoryDisplay")
        self.setDirectoryButton = QtWidgets.QPushButton(self.frameProcessingGroupBox)
        self.setDirectoryButton.setGeometry(QtCore.QRect(260, 20, 61, 23))
        self.setDirectoryButton.setObjectName("setDirectoryButton")
        self.calibrateLocalCheckBox = QtWidgets.QCheckBox(self.frameProcessingGroupBox)
        self.calibrateLocalCheckBox.setGeometry(QtCore.QRect(120, 80, 131, 20))
        self.calibrateLocalCheckBox.setObjectName("calibrateLocalCheckBox")
        self.groupBox_14 = QtWidgets.QGroupBox(self.frameProcessingGroupBox)
        self.groupBox_14.setGeometry(QtCore.QRect(370, 10, 101, 91))
        self.groupBox_14.setObjectName("groupBox_14")
        self.mergeNoneRadioButton = QtWidgets.QRadioButton(self.groupBox_14)
        self.mergeNoneRadioButton.setGeometry(QtCore.QRect(20, 20, 61, 17))
        self.mergeNoneRadioButton.setChecked(True)
        self.mergeNoneRadioButton.setObjectName("mergeNoneRadioButton")
        self.mergeMertensRadioButton = QtWidgets.QRadioButton(self.groupBox_14)
        self.mergeMertensRadioButton.setGeometry(QtCore.QRect(20, 40, 61, 17))
        self.mergeMertensRadioButton.setObjectName("mergeMertensRadioButton")
        self.mergeDebevecRadioButton = QtWidgets.QRadioButton(self.groupBox_14)
        self.mergeDebevecRadioButton.setGeometry(QtCore.QRect(20, 60, 71, 17))
        self.mergeDebevecRadioButton.setObjectName("mergeDebevecRadioButton")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frameProcessingGroupBox)
        self.groupBox_12.setGeometry(QtCore.QRect(480, 10, 141, 91))
        self.groupBox_12.setObjectName("groupBox_12")
        self.histosCheckBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.histosCheckBox.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.histosCheckBox.setObjectName("histosCheckBox")
        self.sharpnessCheckBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.sharpnessCheckBox.setGeometry(QtCore.QRect(10, 40, 121, 20))
        self.sharpnessCheckBox.setObjectName("sharpnessCheckBox")
        self.reduceFactorBox = QtWidgets.QSpinBox(self.groupBox_12)
        self.reduceFactorBox.setGeometry(QtCore.QRect(10, 60, 37, 20))
        self.reduceFactorBox.setMinimum(1)
        self.reduceFactorBox.setMaximum(20)
        self.reduceFactorBox.setSingleStep(1)
        self.reduceFactorBox.setProperty("value", 1)
        self.reduceFactorBox.setObjectName("reduceFactorBox")
        self.label_32 = QtWidgets.QLabel(self.groupBox_12)
        self.label_32.setGeometry(QtCore.QRect(60, 60, 61, 16))
        self.label_32.setObjectName("label_32")
        self.motorSettingsGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.motorSettingsGroupBox.setGeometry(QtCore.QRect(10, 630, 631, 81))
        self.motorSettingsGroupBox.setStyleSheet("QGroupBox#motorSettingsGroupBox { \n"
"     border: 1px solid black; \n"
" } ")
        self.motorSettingsGroupBox.setObjectName("motorSettingsGroupBox")
        self.pulleyRatioBox = QtWidgets.QDoubleSpinBox(self.motorSettingsGroupBox)
        self.pulleyRatioBox.setGeometry(QtCore.QRect(130, 50, 62, 22))
        self.pulleyRatioBox.setMinimum(0.25)
        self.pulleyRatioBox.setMaximum(4.0)
        self.pulleyRatioBox.setSingleStep(0.25)
        self.pulleyRatioBox.setProperty("value", 1.0)
        self.pulleyRatioBox.setObjectName("pulleyRatioBox")
        self.label_18 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_18.setObjectName("label_18")
        self.stepsPerRevBox = QtWidgets.QSpinBox(self.motorSettingsGroupBox)
        self.stepsPerRevBox.setGeometry(QtCore.QRect(130, 20, 61, 22))
        self.stepsPerRevBox.setMaximum(12000)
        self.stepsPerRevBox.setSingleStep(200)
        self.stepsPerRevBox.setProperty("value", 200)
        self.stepsPerRevBox.setObjectName("stepsPerRevBox")
        self.label_20 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_20.setGeometry(QtCore.QRect(20, 50, 111, 20))
        self.label_20.setObjectName("label_20")
        self.label_11 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_11.setGeometry(QtCore.QRect(200, 20, 47, 13))
        self.label_11.setObjectName("label_11")
        self.pulseEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.pulseEdit.setGeometry(QtCore.QRect(310, 20, 31, 16))
        self.pulseEdit.setObjectName("pulseEdit")
        self.dirEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.dirEdit.setGeometry(QtCore.QRect(370, 20, 31, 16))
        self.dirEdit.setObjectName("dirEdit")
        self.label_13 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_13.setGeometry(QtCore.QRect(270, 20, 41, 16))
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_19.setGeometry(QtCore.QRect(350, 20, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_25 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_25.setGeometry(QtCore.QRect(420, 20, 47, 13))
        self.label_25.setObjectName("label_25")
        self.triggerEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.triggerEdit.setGeometry(QtCore.QRect(470, 20, 31, 16))
        self.triggerEdit.setObjectName("triggerEdit")
        self.setMotorButton = QtWidgets.QPushButton(self.motorSettingsGroupBox)
        self.setMotorButton.setGeometry(QtCore.QRect(520, 20, 75, 23))
        self.setMotorButton.setObjectName("setMotorButton")
        self.enaEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.enaEdit.setGeometry(QtCore.QRect(230, 20, 31, 16))
        self.enaEdit.setObjectName("enaEdit")
        self.enaLevelCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.enaLevelCheckBox.setGeometry(QtCore.QRect(230, 40, 41, 17))
        self.enaLevelCheckBox.setObjectName("enaLevelCheckBox")
        self.dirLevelCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.dirLevelCheckBox.setGeometry(QtCore.QRect(370, 40, 41, 17))
        self.dirLevelCheckBox.setObjectName("dirLevelCheckBox")
        self.triggerLevelCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.triggerLevelCheckBox.setGeometry(QtCore.QRect(470, 40, 41, 17))
        self.triggerLevelCheckBox.setObjectName("triggerLevelCheckBox")
        self.afterTriggerCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.afterTriggerCheckBox.setGeometry(QtCore.QRect(470, 60, 91, 17))
        self.afterTriggerCheckBox.setObjectName("afterTriggerCheckBox")
        self.cameraSettingsGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.cameraSettingsGroupBox.setGeometry(QtCore.QRect(10, 720, 631, 171))
        self.cameraSettingsGroupBox.setStyleSheet("QGroupBox#cameraSettingsGroupBox { \n"
"     border: 1px solid black; \n"
" } ")
        self.cameraSettingsGroupBox.setObjectName("cameraSettingsGroupBox")
        self.label = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label.setGeometry(QtCore.QRect(110, 20, 25, 16))
        self.label.setObjectName("label")
        self.awbModeBox = QtWidgets.QComboBox(self.cameraSettingsGroupBox)
        self.awbModeBox.setGeometry(QtCore.QRect(180, 20, 89, 20))
        self.awbModeBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.awbModeBox.setObjectName("awbModeBox")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(0, "off")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(1, "auto")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(2, "sunlight")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(3, "cloudy")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.redGainBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.redGainBox.setEnabled(True)
        self.redGainBox.setGeometry(QtCore.QRect(280, 20, 41, 18))
        self.redGainBox.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.redGainBox.setMinimum(50)
        self.redGainBox.setMaximum(400)
        self.redGainBox.setSingleStep(10)
        self.redGainBox.setProperty("value", 100)
        self.redGainBox.setObjectName("redGainBox")
        self.blueGainBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.blueGainBox.setEnabled(True)
        self.blueGainBox.setGeometry(QtCore.QRect(340, 20, 41, 18))
        self.blueGainBox.setStyleSheet("background-color: rgba(0, 0, 255, 100);")
        self.blueGainBox.setMinimum(50)
        self.blueGainBox.setMaximum(400)
        self.blueGainBox.setSingleStep(10)
        self.blueGainBox.setProperty("value", 100)
        self.blueGainBox.setObjectName("blueGainBox")
        self.setColorsButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setColorsButton.setGeometry(QtCore.QRect(520, 20, 75, 23))
        self.setColorsButton.setObjectName("setColorsButton")
        self.label_2 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 50, 36, 16))
        self.label_2.setObjectName("label_2")
        self.shutterSpeedBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.shutterSpeedBox.setGeometry(QtCore.QRect(180, 50, 61, 20))
        self.shutterSpeedBox.setMaximum(100000)
        self.shutterSpeedBox.setSingleStep(1000)
        self.shutterSpeedBox.setProperty("value", 0)
        self.shutterSpeedBox.setObjectName("shutterSpeedBox")
        self.setShutterSpeedButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setShutterSpeedButton.setGeometry(QtCore.QRect(520, 50, 75, 23))
        self.setShutterSpeedButton.setObjectName("setShutterSpeedButton")
        self.setGainsButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setGainsButton.setGeometry(QtCore.QRect(520, 80, 75, 23))
        self.setGainsButton.setObjectName("setGainsButton")
        self.exposureSpeedLabel = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.exposureSpeedLabel.setGeometry(QtCore.QRect(310, 50, 61, 16))
        self.exposureSpeedLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.exposureSpeedLabel.setText("")
        self.exposureSpeedLabel.setObjectName("exposureSpeedLabel")
        self.autoExposureCheckBox = QtWidgets.QCheckBox(self.cameraSettingsGroupBox)
        self.autoExposureCheckBox.setGeometry(QtCore.QRect(260, 50, 46, 17))
        self.autoExposureCheckBox.setObjectName("autoExposureCheckBox")
        self.label_4 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 51, 41))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.digitalGainLabel = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.digitalGainLabel.setGeometry(QtCore.QRect(370, 80, 41, 21))
        self.digitalGainLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.digitalGainLabel.setText("")
        self.digitalGainLabel.setObjectName("digitalGainLabel")
        self.analogGainLabel = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.analogGainLabel.setGeometry(QtCore.QRect(470, 80, 41, 21))
        self.analogGainLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.analogGainLabel.setText("")
        self.analogGainLabel.setObjectName("analogGainLabel")
        self.label_7 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_7.setGeometry(QtCore.QRect(330, 70, 41, 41))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_8.setGeometry(QtCore.QRect(420, 70, 41, 41))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.exposureModeBox = QtWidgets.QComboBox(self.cameraSettingsGroupBox)
        self.exposureModeBox.setGeometry(QtCore.QRect(100, 80, 71, 20))
        self.exposureModeBox.setObjectName("exposureModeBox")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.setItemText(1, "off")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.addItem("")
        self.brightnessBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.brightnessBox.setGeometry(QtCore.QRect(230, 110, 43, 20))
        self.brightnessBox.setMaximum(100)
        self.brightnessBox.setSingleStep(1)
        self.brightnessBox.setProperty("value", 50)
        self.brightnessBox.setObjectName("brightnessBox")
        self.contrastBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.contrastBox.setGeometry(QtCore.QRect(340, 110, 47, 20))
        self.contrastBox.setMinimum(-100)
        self.contrastBox.setMaximum(100)
        self.contrastBox.setSingleStep(1)
        self.contrastBox.setProperty("value", 0)
        self.contrastBox.setObjectName("contrastBox")
        self.label_5 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 110, 50, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_6.setGeometry(QtCore.QRect(280, 110, 42, 16))
        self.label_6.setObjectName("label_6")
        self.setCorrectionsButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setCorrectionsButton.setGeometry(QtCore.QRect(520, 110, 75, 23))
        self.setCorrectionsButton.setObjectName("setCorrectionsButton")
        self.label_10 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_10.setGeometry(QtCore.QRect(400, 110, 50, 16))
        self.label_10.setObjectName("label_10")
        self.saturationBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.saturationBox.setGeometry(QtCore.QRect(460, 110, 47, 21))
        self.saturationBox.setMinimum(-100)
        self.saturationBox.setMaximum(100)
        self.saturationBox.setSingleStep(1)
        self.saturationBox.setProperty("value", 0)
        self.saturationBox.setObjectName("saturationBox")
        self.isoBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.isoBox.setGeometry(QtCore.QRect(460, 140, 51, 20))
        self.isoBox.setMaximum(800)
        self.isoBox.setSingleStep(100)
        self.isoBox.setProperty("value", 100)
        self.isoBox.setObjectName("isoBox")
        self.label_14 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_14.setGeometry(QtCore.QRect(420, 140, 16, 16))
        self.label_14.setObjectName("label_14")
        self.setIsoButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setIsoButton.setGeometry(QtCore.QRect(520, 140, 75, 23))
        self.setIsoButton.setObjectName("setIsoButton")
        self.exposureCompensationBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.exposureCompensationBox.setGeometry(QtCore.QRect(470, 50, 41, 20))
        self.exposureCompensationBox.setMinimum(-25)
        self.exposureCompensationBox.setMaximum(25)
        self.exposureCompensationBox.setSingleStep(1)
        self.exposureCompensationBox.setProperty("value", 0)
        self.exposureCompensationBox.setObjectName("exposureCompensationBox")
        self.label_15 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_15.setGeometry(QtCore.QRect(390, 50, 66, 16))
        self.label_15.setObjectName("label_15")
        self.getCameraSettingsButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.getCameraSettingsButton.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.getCameraSettingsButton.setObjectName("getCameraSettingsButton")
        self.meterModeBox = QtWidgets.QComboBox(self.cameraSettingsGroupBox)
        self.meterModeBox.setGeometry(QtCore.QRect(240, 80, 71, 20))
        self.meterModeBox.setObjectName("meterModeBox")
        self.meterModeBox.addItem("")
        self.meterModeBox.addItem("")
        self.meterModeBox.addItem("")
        self.meterModeBox.addItem("")
        self.label_35 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_35.setGeometry(QtCore.QRect(190, 70, 51, 41))
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.sharpnessBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.sharpnessBox.setGeometry(QtCore.QRect(340, 140, 51, 20))
        self.sharpnessBox.setMinimum(-100)
        self.sharpnessBox.setMaximum(100)
        self.sharpnessBox.setSingleStep(10)
        self.sharpnessBox.setProperty("value", 0)
        self.sharpnessBox.setObjectName("sharpnessBox")
        self.label_41 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_41.setGeometry(QtCore.QRect(265, 140, 51, 20))
        self.label_41.setObjectName("label_41")
        self.lensAnalyseGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.lensAnalyseGroupBox.setGeometry(QtCore.QRect(10, 900, 631, 51))
        self.lensAnalyseGroupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.lensAnalyseGroupBox.setObjectName("lensAnalyseGroupBox")
        self.lensAnalyseButton = QtWidgets.QPushButton(self.lensAnalyseGroupBox)
        self.lensAnalyseButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.lensAnalyseButton.setObjectName("lensAnalyseButton")
        self.calibrateButton = QtWidgets.QPushButton(self.lensAnalyseGroupBox)
        self.calibrateButton.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.calibrateButton.setObjectName("calibrateButton")
        self.calibrateLocalButton = QtWidgets.QPushButton(self.lensAnalyseGroupBox)
        self.calibrateLocalButton.setGeometry(QtCore.QRect(180, 20, 91, 23))
        self.calibrateLocalButton.setObjectName("calibrateLocalButton")
        self.whiteBalanceButton = QtWidgets.QPushButton(self.lensAnalyseGroupBox)
        self.whiteBalanceButton.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.whiteBalanceButton.setObjectName("whiteBalanceButton")
        self.messageTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.messageTextEdit.setGeometry(QtCore.QRect(10, 960, 631, 71))
        self.messageTextEdit.setObjectName("messageTextEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(TelecineDialog)
        self.awbModeBox.setCurrentIndex(0)
        self.exposureModeBox.setCurrentIndex(0)
        self.meterModeBox.setCurrentIndex(0)
        self.takeImageButton.clicked.connect(TelecineDialog.takeImage)
        self.captureStopButton.clicked.connect(TelecineDialog.captureStop)
        self.setShutterSpeedButton.clicked.connect(TelecineDialog.setShutterSpeed)
        self.setGainsButton.clicked.connect(TelecineDialog.setFrameRate)
        self.autoExposureCheckBox.stateChanged['int'].connect(TelecineDialog.setAutoExposure)
        self.forwardOneButton.clicked.connect(TelecineDialog.forwardOne)
        self.backwardOneButton.clicked.connect(TelecineDialog.backwardOne)
        self.forwardButton.clicked.connect(TelecineDialog.forward)
        self.backwardButton.clicked.connect(TelecineDialog.backward)
        self.motorStopButton.clicked.connect(TelecineDialog.motorStop)
        self.setCorrectionsButton.clicked['bool'].connect(TelecineDialog.setCorrections)
        self.saveCheckBox.stateChanged['int'].connect(TelecineDialog.setSave)
        self.setIsoButton.clicked.connect(TelecineDialog.setIso)
        self.getCameraSettingsButton.clicked.connect(TelecineDialog.getCameraSettings)
        self.chooseDirectoryButton.clicked.connect(TelecineDialog.chooseDirectory)
        self.sharpnessCheckBox.stateChanged['int'].connect(TelecineDialog.setSharpness)
        self.histosCheckBox.stateChanged['int'].connect(TelecineDialog.setHistos)
        self.connectButton.clicked['bool'].connect(TelecineDialog.connectDisconnect)
        self.openCameraButton.clicked.connect(TelecineDialog.openCamera)
        self.setMotorButton.clicked.connect(TelecineDialog.setMotorInitSettings)
        self.captureStartButton.clicked.connect(TelecineDialog.captureStart)
        self.setDirectoryButton.clicked.connect(TelecineDialog.setDirectory)
        self.closeCameraButton.clicked.connect(TelecineDialog.closeCamera)
        self.reduceFactorBox.valueChanged['int'].connect(TelecineDialog.setReduce)
        self.calibrateButton.clicked.connect(TelecineDialog.calibrate)
        self.motorOnButton.clicked.connect(TelecineDialog.motorOn)
        self.motorOffButton.clicked.connect(TelecineDialog.motorOff)
        self.capturePauseButton.clicked.connect(TelecineDialog.capturePause)
        self.autoPauseCheckBox.stateChanged['int'].connect(TelecineDialog.setAutoPause)
        self.mergeDebevecRadioButton.toggled['bool'].connect(TelecineDialog.setMerge)
        self.mergeNoneRadioButton.toggled['bool'].connect(TelecineDialog.setMerge)
        self.mergeMertensRadioButton.toggled['bool'].connect(TelecineDialog.setMerge)
        self.setGainsButton.clicked.connect(TelecineDialog.setGains)
        self.setColorsButton.clicked.connect(TelecineDialog.setColors)
        self.motorOnTriggerButton.clicked.connect(TelecineDialog.motorOnTrigger)
        self.lensAnalyseButton.clicked.connect(TelecineDialog.lensAnalyse)
        self.ROIwBox.editingFinished.connect(TelecineDialog.ROIwChanged)
        self.ROIhBox.editingFinished.connect(TelecineDialog.ROIhChanged)
        self.setROIButton.clicked.connect(TelecineDialog.setROI)
        self.resetROIButton.clicked.connect(TelecineDialog.resetROI)
        self.calibrateLocalButton.clicked.connect(TelecineDialog.calibrateLocal)
        self.calibrateLocalCheckBox.stateChanged['int'].connect(TelecineDialog.doCalibrateLocal)
        self.whiteBalanceButton.clicked.connect(TelecineDialog.setWhiteBalance)
        self.motorCalibrateButton.clicked.connect(TelecineDialog.motorCalibrate)
        self.maxFpsButton.clicked.connect(TelecineDialog.maxFps)
        self.onTriggerButton.toggled['bool'].connect(TelecineDialog.setOnTrigger)
        self.maxSpeedButton.clicked.connect(TelecineDialog.maxSpeed)
        QtCore.QMetaObject.connectSlotsByName(TelecineDialog)

    def retranslateUi(self, TelecineDialog):
        _translate = QtCore.QCoreApplication.translate
        TelecineDialog.setWindowTitle(_translate("TelecineDialog", "CamDialog"))
        self.initGroupBox.setTitle(_translate("TelecineDialog", "Initialization"))
        self.cameraGroupBox.setTitle(_translate("TelecineDialog", "Camera"))
        self.label_16.setText(_translate("TelecineDialog", "Mode"))
        self.label_9.setText(_translate("TelecineDialog", "HRes"))
        self.openCameraButton.setText(_translate("TelecineDialog", "Open"))
        self.closeCameraButton.setText(_translate("TelecineDialog", "Close"))
        self.hflipCheckBox.setText(_translate("TelecineDialog", "Hflip"))
        self.vflipCheckBox.setText(_translate("TelecineDialog", "Vflip"))
        self.groupBox_3.setTitle(_translate("TelecineDialog", "Calibration"))
        self.calibrateNoneButton.setText(_translate("TelecineDialog", "None"))
        self.calibrateFlatButton.setText(_translate("TelecineDialog", "Flat"))
        self.calibrateTableButton.setText(_translate("TelecineDialog", "Calibrated"))
        self.label_22.setText(_translate("TelecineDialog", "VRes"))
        self.groupBox.setTitle(_translate("TelecineDialog", "Raspberry"))
        self.connectButton.setText(_translate("TelecineDialog", "Connect"))
        self.ipLineEdit.setText(_translate("TelecineDialog", "192.168.0.22"))
        self.motorOnGroupBox.setTitle(_translate("TelecineDialog", "Motor"))
        self.motorOnButton.setText(_translate("TelecineDialog", "On"))
        self.motorOffButton.setText(_translate("TelecineDialog", "Off"))
        self.motorControlGroupBox.setTitle(_translate("TelecineDialog", "Motor control"))
        self.forwardButton.setText(_translate("TelecineDialog", "Fwd"))
        self.backwardButton.setText(_translate("TelecineDialog", "Bck"))
        self.motorStopButton.setText(_translate("TelecineDialog", "Stop"))
        self.forwardOneButton.setText(_translate("TelecineDialog", "FwdOne"))
        self.backwardOneButton.setText(_translate("TelecineDialog", "BwkOne"))
        self.label_17.setText(_translate("TelecineDialog", "Speed"))
        self.motorOnTriggerButton.setText(_translate("TelecineDialog", "On trigger"))
        self.motorCalibrateButton.setText(_translate("TelecineDialog", "Calibrate"))
        self.cameraControlGroupBox.setTitle(_translate("TelecineDialog", "Camera control"))
        self.takeImageButton.setText(_translate("TelecineDialog", "Shot"))
        self.captureStopButton.setText(_translate("TelecineDialog", "Stop"))
        self.captureStartButton.setText(_translate("TelecineDialog", "Capture"))
        self.groupBox_5.setTitle(_translate("TelecineDialog", "Capture parameters"))
        self.playButton.setText(_translate("TelecineDialog", "Preview"))
        self.onFrameButton.setText(_translate("TelecineDialog", "OnFrame"))
        self.onTriggerButton.setText(_translate("TelecineDialog", "OnTrigger"))
        self.label_31.setText(_translate("TelecineDialog", "Framerate"))
        self.label_29.setText(_translate("TelecineDialog", "Motor speed"))
        self.label_24.setText(_translate("TelecineDialog", "Wait before"))
        self.label_34.setText(_translate("TelecineDialog", "frames"))
        self.bracketCheckBox.setText(_translate("TelecineDialog", "Bracket "))
        self.label_12.setText(_translate("TelecineDialog", "Dark"))
        self.label_21.setText(_translate("TelecineDialog", "Light"))
        self.label_23.setText(_translate("TelecineDialog", "Wait between"))
        self.label_26.setText(_translate("TelecineDialog", "frames"))
        self.groupBox_2.setTitle(_translate("TelecineDialog", "ROI"))
        self.resetROIButton.setText(_translate("TelecineDialog", "Reset"))
        self.setROIButton.setText(_translate("TelecineDialog", "Set"))
        self.label_30.setText(_translate("TelecineDialog", "x"))
        self.label_36.setText(_translate("TelecineDialog", "y"))
        self.keepRatioCheckBox.setText(_translate("TelecineDialog", "Keep Ratio"))
        self.centerCheckBox.setText(_translate("TelecineDialog", "Center"))
        self.label_37.setText(_translate("TelecineDialog", "w"))
        self.label_38.setText(_translate("TelecineDialog", "h"))
        self.groupBox_4.setTitle(_translate("TelecineDialog", "Resize"))
        self.resizeCheckBox.setText(_translate("TelecineDialog", "Resize"))
        self.label_39.setText(_translate("TelecineDialog", "w"))
        self.label_40.setText(_translate("TelecineDialog", "h"))
        self.maxFpsButton.setText(_translate("TelecineDialog", "Test"))
        self.maxSpeedButton.setText(_translate("TelecineDialog", "Test"))
        self.capturePauseButton.setText(_translate("TelecineDialog", "Pause"))
        self.autoPauseCheckBox.setText(_translate("TelecineDialog", "Auto pause"))
        self.label_33.setText(_translate("TelecineDialog", "PIN"))
        self.pauseLevelCheckBox.setText(_translate("TelecineDialog", "High"))
        self.frameProcessingGroupBox.setTitle(_translate("TelecineDialog", "Frame processing"))
        self.saveCheckBox.setText(_translate("TelecineDialog", "Save"))
        self.chooseDirectoryButton.setText(_translate("TelecineDialog", "Directory"))
        self.label_27.setText(_translate("TelecineDialog", "Tape"))
        self.label_28.setText(_translate("TelecineDialog", "Clip"))
        self.setDirectoryButton.setText(_translate("TelecineDialog", "Set"))
        self.calibrateLocalCheckBox.setText(_translate("TelecineDialog", "Calibrate Local"))
        self.groupBox_14.setTitle(_translate("TelecineDialog", "Merge"))
        self.mergeNoneRadioButton.setText(_translate("TelecineDialog", "None"))
        self.mergeMertensRadioButton.setText(_translate("TelecineDialog", "Mertens"))
        self.mergeDebevecRadioButton.setText(_translate("TelecineDialog", "Debevec"))
        self.groupBox_12.setTitle(_translate("TelecineDialog", "Display"))
        self.histosCheckBox.setText(_translate("TelecineDialog", "Histos"))
        self.sharpnessCheckBox.setText(_translate("TelecineDialog", "Sharpness"))
        self.label_32.setText(_translate("TelecineDialog", "Reduce "))
        self.motorSettingsGroupBox.setTitle(_translate("TelecineDialog", "Motor settings"))
        self.label_18.setText(_translate("TelecineDialog", "Steps per Rev"))
        self.label_20.setText(_translate("TelecineDialog", "Motor/Frame ratio"))
        self.label_11.setText(_translate("TelecineDialog", "ON"))
        self.label_13.setText(_translate("TelecineDialog", "PULSE"))
        self.label_19.setText(_translate("TelecineDialog", "DIR"))
        self.label_25.setText(_translate("TelecineDialog", "TRIGGER"))
        self.setMotorButton.setText(_translate("TelecineDialog", "Set"))
        self.enaLevelCheckBox.setText(_translate("TelecineDialog", "High"))
        self.dirLevelCheckBox.setText(_translate("TelecineDialog", "High"))
        self.triggerLevelCheckBox.setText(_translate("TelecineDialog", "High"))
        self.afterTriggerCheckBox.setText(_translate("TelecineDialog", "Advance after"))
        self.cameraSettingsGroupBox.setTitle(_translate("TelecineDialog", "Camera settings"))
        self.label.setText(_translate("TelecineDialog", "Color"))
        self.awbModeBox.setItemText(4, _translate("TelecineDialog", "shade"))
        self.awbModeBox.setItemText(5, _translate("TelecineDialog", "tungsten"))
        self.awbModeBox.setItemText(6, _translate("TelecineDialog", "fluorescent"))
        self.awbModeBox.setItemText(7, _translate("TelecineDialog", "incandescent"))
        self.awbModeBox.setItemText(8, _translate("TelecineDialog", "flash"))
        self.awbModeBox.setItemText(9, _translate("TelecineDialog", "horizon"))
        self.setColorsButton.setText(_translate("TelecineDialog", "Set"))
        self.label_2.setText(_translate("TelecineDialog", "Shutter"))
        self.setShutterSpeedButton.setText(_translate("TelecineDialog", "Set"))
        self.setGainsButton.setText(_translate("TelecineDialog", "Set"))
        self.autoExposureCheckBox.setText(_translate("TelecineDialog", "Auto"))
        self.label_4.setText(_translate("TelecineDialog", "Exposure mode"))
        self.label_7.setText(_translate("TelecineDialog", "Digital gain"))
        self.label_8.setText(_translate("TelecineDialog", "Analog gain"))
        self.exposureModeBox.setCurrentText(_translate("TelecineDialog", "auto"))
        self.exposureModeBox.setItemText(0, _translate("TelecineDialog", "auto"))
        self.exposureModeBox.setItemText(2, _translate("TelecineDialog", "night"))
        self.exposureModeBox.setItemText(3, _translate("TelecineDialog", "nightpreview"))
        self.exposureModeBox.setItemText(4, _translate("TelecineDialog", "backlight"))
        self.exposureModeBox.setItemText(5, _translate("TelecineDialog", "spotlight"))
        self.exposureModeBox.setItemText(6, _translate("TelecineDialog", "sports"))
        self.exposureModeBox.setItemText(7, _translate("TelecineDialog", "snow"))
        self.exposureModeBox.setItemText(8, _translate("TelecineDialog", "beach"))
        self.exposureModeBox.setItemText(9, _translate("TelecineDialog", "verylong"))
        self.exposureModeBox.setItemText(10, _translate("TelecineDialog", "fixedfps"))
        self.exposureModeBox.setItemText(11, _translate("TelecineDialog", "antishake"))
        self.exposureModeBox.setItemText(12, _translate("TelecineDialog", "fireworks"))
        self.label_5.setText(_translate("TelecineDialog", "Brightness"))
        self.label_6.setText(_translate("TelecineDialog", "Contrast"))
        self.setCorrectionsButton.setText(_translate("TelecineDialog", "Set"))
        self.label_10.setText(_translate("TelecineDialog", "Saturation"))
        self.label_14.setText(_translate("TelecineDialog", "Iso"))
        self.setIsoButton.setText(_translate("TelecineDialog", "Set"))
        self.label_15.setText(_translate("TelecineDialog", "compensation"))
        self.getCameraSettingsButton.setText(_translate("TelecineDialog", "Get Settings"))
        self.meterModeBox.setCurrentText(_translate("TelecineDialog", "average"))
        self.meterModeBox.setItemText(0, _translate("TelecineDialog", "average"))
        self.meterModeBox.setItemText(1, _translate("TelecineDialog", "spot"))
        self.meterModeBox.setItemText(2, _translate("TelecineDialog", "backlit"))
        self.meterModeBox.setItemText(3, _translate("TelecineDialog", "matrix"))
        self.label_35.setText(_translate("TelecineDialog", "Meter mode"))
        self.label_41.setText(_translate("TelecineDialog", "Sharpness"))
        self.lensAnalyseGroupBox.setTitle(_translate("TelecineDialog", "Lens analyse"))
        self.lensAnalyseButton.setText(_translate("TelecineDialog", "Analyse"))
        self.calibrateButton.setText(_translate("TelecineDialog", "Calibrate"))
        self.calibrateLocalButton.setText(_translate("TelecineDialog", "Calibrate Local"))
        self.whiteBalanceButton.setText(_translate("TelecineDialog", "WB"))

