# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelecineDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TelecineDialog(object):
    def setupUi(self, TelecineDialog):
        TelecineDialog.setObjectName("TelecineDialog")
        TelecineDialog.resize(1332, 1041)
        self.cameraSettingsGroupBox = QtWidgets.QGroupBox(TelecineDialog)
        self.cameraSettingsGroupBox.setGeometry(QtCore.QRect(20, 730, 591, 241))
        self.cameraSettingsGroupBox.setObjectName("cameraSettingsGroupBox")
        self.label = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label.setGeometry(QtCore.QRect(20, 70, 25, 16))
        self.label.setObjectName("label")
        self.awbModeBox = QtWidgets.QComboBox(self.cameraSettingsGroupBox)
        self.awbModeBox.setGeometry(QtCore.QRect(50, 70, 89, 20))
        self.awbModeBox.setObjectName("awbModeBox")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(0, "off")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(1, "auto")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(2, "sunlight")
        self.awbModeBox.addItem("")
        self.awbModeBox.setItemText(3, "cloudy")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.awbModeBox.addItem("")
        self.redGainBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.redGainBox.setEnabled(True)
        self.redGainBox.setGeometry(QtCore.QRect(150, 70, 41, 18))
        self.redGainBox.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.redGainBox.setMinimum(50)
        self.redGainBox.setMaximum(400)
        self.redGainBox.setSingleStep(10)
        self.redGainBox.setProperty("value", 100)
        self.redGainBox.setObjectName("redGainBox")
        self.blueGainBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.blueGainBox.setEnabled(True)
        self.blueGainBox.setGeometry(QtCore.QRect(210, 70, 41, 18))
        self.blueGainBox.setStyleSheet("background-color: rgba(0, 0, 255, 100);")
        self.blueGainBox.setMinimum(50)
        self.blueGainBox.setMaximum(400)
        self.blueGainBox.setSingleStep(10)
        self.blueGainBox.setProperty("value", 100)
        self.blueGainBox.setObjectName("blueGainBox")
        self.setGainsButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setGainsButton.setGeometry(QtCore.QRect(400, 70, 75, 23))
        self.setGainsButton.setObjectName("setGainsButton")
        self.label_2 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 36, 16))
        self.label_2.setObjectName("label_2")
        self.shutterSpeedBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.shutterSpeedBox.setGeometry(QtCore.QRect(70, 100, 61, 20))
        self.shutterSpeedBox.setMaximum(100000)
        self.shutterSpeedBox.setSingleStep(1000)
        self.shutterSpeedBox.setProperty("value", 20000)
        self.shutterSpeedBox.setObjectName("shutterSpeedBox")
        self.setShutterSpeedButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setShutterSpeedButton.setGeometry(QtCore.QRect(400, 100, 75, 23))
        self.setShutterSpeedButton.setObjectName("setShutterSpeedButton")
        self.setFrameRateButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setFrameRateButton.setGeometry(QtCore.QRect(400, 130, 75, 23))
        self.setFrameRateButton.setObjectName("setFrameRateButton")
        self.exposureSpeedLabel = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.exposureSpeedLabel.setGeometry(QtCore.QRect(190, 100, 61, 16))
        self.exposureSpeedLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.exposureSpeedLabel.setText("")
        self.exposureSpeedLabel.setObjectName("exposureSpeedLabel")
        self.autoExposureCheckBox = QtWidgets.QCheckBox(self.cameraSettingsGroupBox)
        self.autoExposureCheckBox.setGeometry(QtCore.QRect(140, 100, 46, 17))
        self.autoExposureCheckBox.setObjectName("autoExposureCheckBox")
        self.label_4 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 26, 16))
        self.label_4.setObjectName("label_4")
        self.digitalGainLabel = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.digitalGainLabel.setGeometry(QtCore.QRect(170, 130, 41, 16))
        self.digitalGainLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.digitalGainLabel.setText("")
        self.digitalGainLabel.setObjectName("digitalGainLabel")
        self.analogGainLabel = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.analogGainLabel.setGeometry(QtCore.QRect(270, 130, 71, 21))
        self.analogGainLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.analogGainLabel.setText("")
        self.analogGainLabel.setObjectName("analogGainLabel")
        self.label_7 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_7.setGeometry(QtCore.QRect(130, 130, 29, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_8.setGeometry(QtCore.QRect(220, 130, 33, 16))
        self.label_8.setObjectName("label_8")
        self.exposureModeBox = QtWidgets.QComboBox(self.cameraSettingsGroupBox)
        self.exposureModeBox.setGeometry(QtCore.QRect(70, 130, 48, 20))
        self.exposureModeBox.setObjectName("exposureModeBox")
        self.exposureModeBox.addItem("")
        self.exposureModeBox.setItemText(0, "off")
        self.exposureModeBox.addItem("")
        self.brightnessBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.brightnessBox.setGeometry(QtCore.QRect(70, 170, 43, 20))
        self.brightnessBox.setMaximum(100)
        self.brightnessBox.setSingleStep(10)
        self.brightnessBox.setProperty("value", 50)
        self.brightnessBox.setObjectName("brightnessBox")
        self.contrastBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.contrastBox.setGeometry(QtCore.QRect(170, 170, 47, 20))
        self.contrastBox.setMinimum(-100)
        self.contrastBox.setMaximum(100)
        self.contrastBox.setSingleStep(10)
        self.contrastBox.setProperty("value", 0)
        self.contrastBox.setObjectName("contrastBox")
        self.label_5 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 50, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_6.setGeometry(QtCore.QRect(120, 170, 42, 16))
        self.label_6.setObjectName("label_6")
        self.autoGetSettingsCheckBox = QtWidgets.QCheckBox(self.cameraSettingsGroupBox)
        self.autoGetSettingsCheckBox.setGeometry(QtCore.QRect(130, 30, 70, 17))
        self.autoGetSettingsCheckBox.setObjectName("autoGetSettingsCheckBox")
        self.setCorrectionsButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setCorrectionsButton.setGeometry(QtCore.QRect(400, 160, 75, 23))
        self.setCorrectionsButton.setObjectName("setCorrectionsButton")
        self.label_10 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_10.setGeometry(QtCore.QRect(230, 170, 50, 16))
        self.label_10.setObjectName("label_10")
        self.saturationBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.saturationBox.setGeometry(QtCore.QRect(290, 170, 47, 20))
        self.saturationBox.setMinimum(-100)
        self.saturationBox.setMaximum(100)
        self.saturationBox.setSingleStep(10)
        self.saturationBox.setProperty("value", 0)
        self.saturationBox.setObjectName("saturationBox")
        self.isoBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.isoBox.setGeometry(QtCore.QRect(40, 200, 43, 20))
        self.isoBox.setMaximum(800)
        self.isoBox.setSingleStep(100)
        self.isoBox.setProperty("value", 0)
        self.isoBox.setObjectName("isoBox")
        self.label_14 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 200, 16, 16))
        self.label_14.setObjectName("label_14")
        self.setIsoButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.setIsoButton.setGeometry(QtCore.QRect(400, 200, 75, 23))
        self.setIsoButton.setObjectName("setIsoButton")
        self.exposureCompensationBox = QtWidgets.QSpinBox(self.cameraSettingsGroupBox)
        self.exposureCompensationBox.setGeometry(QtCore.QRect(340, 100, 41, 20))
        self.exposureCompensationBox.setMinimum(-25)
        self.exposureCompensationBox.setMaximum(25)
        self.exposureCompensationBox.setSingleStep(1)
        self.exposureCompensationBox.setProperty("value", 0)
        self.exposureCompensationBox.setObjectName("exposureCompensationBox")
        self.label_15 = QtWidgets.QLabel(self.cameraSettingsGroupBox)
        self.label_15.setGeometry(QtCore.QRect(260, 100, 66, 16))
        self.label_15.setObjectName("label_15")
        self.getCameraSettingsButton = QtWidgets.QPushButton(self.cameraSettingsGroupBox)
        self.getCameraSettingsButton.setGeometry(QtCore.QRect(30, 30, 81, 21))
        self.getCameraSettingsButton.setObjectName("getCameraSettingsButton")
        self.cameraControlGroupBox = QtWidgets.QGroupBox(TelecineDialog)
        self.cameraControlGroupBox.setGeometry(QtCore.QRect(20, 230, 571, 161))
        self.cameraControlGroupBox.setObjectName("cameraControlGroupBox")
        self.takeImageButton = QtWidgets.QPushButton(self.cameraControlGroupBox)
        self.takeImageButton.setGeometry(QtCore.QRect(20, 20, 61, 23))
        self.takeImageButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.takeImageButton.setObjectName("takeImageButton")
        self.captureStopButton = QtWidgets.QPushButton(self.cameraControlGroupBox)
        self.captureStopButton.setGeometry(QtCore.QRect(190, 20, 61, 23))
        self.captureStopButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.captureStopButton.setObjectName("captureStopButton")
        self.captureStartButton = QtWidgets.QPushButton(self.cameraControlGroupBox)
        self.captureStartButton.setGeometry(QtCore.QRect(110, 20, 61, 23))
        self.captureStartButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.captureStartButton.setObjectName("captureStartButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.cameraControlGroupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 60, 461, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.playButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.playButton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.playButton.setChecked(True)
        self.playButton.setObjectName("playButton")
        self.onFrameButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.onFrameButton.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.onFrameButton.setChecked(False)
        self.onFrameButton.setObjectName("onFrameButton")
        self.onTriggerButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.onTriggerButton.setGeometry(QtCore.QRect(10, 60, 71, 17))
        self.onTriggerButton.setObjectName("onTriggerButton")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(90, 20, 50, 16))
        self.label_3.setObjectName("label_3")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(90, 50, 50, 16))
        self.label_31.setObjectName("label_31")
        self.framerateBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.framerateBox.setGeometry(QtCore.QRect(160, 50, 37, 20))
        self.framerateBox.setMaximum(30)
        self.framerateBox.setSingleStep(1)
        self.framerateBox.setProperty("value", 30)
        self.framerateBox.setObjectName("framerateBox")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(210, 50, 60, 16))
        self.label_29.setObjectName("label_29")
        self.captureMotorSpeedBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.captureMotorSpeedBox.setGeometry(QtCore.QRect(280, 50, 41, 22))
        self.captureMotorSpeedBox.setDecimals(1)
        self.captureMotorSpeedBox.setMinimum(0.0)
        self.captureMotorSpeedBox.setMaximum(10.0)
        self.captureMotorSpeedBox.setSingleStep(0.1)
        self.captureMotorSpeedBox.setProperty("value", 5.0)
        self.captureMotorSpeedBox.setObjectName("captureMotorSpeedBox")
        self.playFramerateBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.playFramerateBox.setGeometry(QtCore.QRect(160, 20, 37, 20))
        self.playFramerateBox.setMaximum(30)
        self.playFramerateBox.setSingleStep(1)
        self.playFramerateBox.setProperty("value", 5)
        self.playFramerateBox.setObjectName("playFramerateBox")
        self.motorControlGroupBox = QtWidgets.QGroupBox(TelecineDialog)
        self.motorControlGroupBox.setGeometry(QtCore.QRect(20, 160, 541, 61))
        self.motorControlGroupBox.setObjectName("motorControlGroupBox")
        self.forwardButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.forwardButton.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.forwardButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.forwardButton.setObjectName("forwardButton")
        self.backwardButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.backwardButton.setGeometry(QtCore.QRect(80, 20, 61, 21))
        self.backwardButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.backwardButton.setObjectName("backwardButton")
        self.motorStopButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.motorStopButton.setGeometry(QtCore.QRect(150, 20, 61, 21))
        self.motorStopButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.motorStopButton.setObjectName("motorStopButton")
        self.forwardOneButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.forwardOneButton.setGeometry(QtCore.QRect(210, 20, 61, 21))
        self.forwardOneButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.forwardOneButton.setObjectName("forwardOneButton")
        self.backwardOneButton = QtWidgets.QPushButton(self.motorControlGroupBox)
        self.backwardOneButton.setGeometry(QtCore.QRect(280, 20, 61, 21))
        self.backwardOneButton.setMaximumSize(QtCore.QSize(61, 16777215))
        self.backwardOneButton.setObjectName("backwardOneButton")
        self.label_17 = QtWidgets.QLabel(self.motorControlGroupBox)
        self.label_17.setGeometry(QtCore.QRect(350, 20, 47, 13))
        self.label_17.setObjectName("label_17")
        self.motorSpeedBox = QtWidgets.QDoubleSpinBox(self.motorControlGroupBox)
        self.motorSpeedBox.setGeometry(QtCore.QRect(390, 20, 41, 22))
        self.motorSpeedBox.setDecimals(1)
        self.motorSpeedBox.setMinimum(0.0)
        self.motorSpeedBox.setMaximum(10.0)
        self.motorSpeedBox.setSingleStep(0.1)
        self.motorSpeedBox.setProperty("value", 5.0)
        self.motorSpeedBox.setObjectName("motorSpeedBox")
        self.lcdDisplayCount = QtWidgets.QLCDNumber(self.motorControlGroupBox)
        self.lcdDisplayCount.setGeometry(QtCore.QRect(450, 20, 64, 23))
        self.lcdDisplayCount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdDisplayCount.setLineWidth(1)
        self.lcdDisplayCount.setDigitCount(5)
        self.lcdDisplayCount.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdDisplayCount.setObjectName("lcdDisplayCount")
        self.groupBox_7 = QtWidgets.QGroupBox(TelecineDialog)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 20, 681, 131))
        self.groupBox_7.setObjectName("groupBox_7")
        self.cameraGroupBox = QtWidgets.QGroupBox(self.groupBox_7)
        self.cameraGroupBox.setGeometry(QtCore.QRect(160, 10, 341, 111))
        self.cameraGroupBox.setObjectName("cameraGroupBox")
        self.label_16 = QtWidgets.QLabel(self.cameraGroupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_16.setObjectName("label_16")
        self.modeBox = QtWidgets.QSpinBox(self.cameraGroupBox)
        self.modeBox.setGeometry(QtCore.QRect(60, 50, 42, 22))
        self.modeBox.setMinimum(0)
        self.modeBox.setMaximum(7)
        self.modeBox.setProperty("value", 4)
        self.modeBox.setObjectName("modeBox")
        self.useCalibrationCheckBox = QtWidgets.QCheckBox(self.cameraGroupBox)
        self.useCalibrationCheckBox.setGeometry(QtCore.QRect(20, 80, 91, 17))
        self.useCalibrationCheckBox.setChecked(True)
        self.useCalibrationCheckBox.setObjectName("useCalibrationCheckBox")
        self.cameraVersionLabel = QtWidgets.QLabel(self.cameraGroupBox)
        self.cameraVersionLabel.setGeometry(QtCore.QRect(260, 50, 71, 16))
        self.cameraVersionLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraVersionLabel.setText("")
        self.cameraVersionLabel.setObjectName("cameraVersionLabel")
        self.cameraResolutionLabel = QtWidgets.QLabel(self.cameraGroupBox)
        self.cameraResolutionLabel.setGeometry(QtCore.QRect(260, 80, 71, 16))
        self.cameraResolutionLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraResolutionLabel.setText("")
        self.cameraResolutionLabel.setObjectName("cameraResolutionLabel")
        self.hresLineEdit = QtWidgets.QLineEdit(self.cameraGroupBox)
        self.hresLineEdit.setGeometry(QtCore.QRect(160, 50, 81, 20))
        self.hresLineEdit.setObjectName("hresLineEdit")
        self.vresLineEdit = QtWidgets.QLineEdit(self.cameraGroupBox)
        self.vresLineEdit.setGeometry(QtCore.QRect(160, 80, 81, 20))
        self.vresLineEdit.setObjectName("vresLineEdit")
        self.label_9 = QtWidgets.QLabel(self.cameraGroupBox)
        self.label_9.setGeometry(QtCore.QRect(120, 50, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_30 = QtWidgets.QLabel(self.cameraGroupBox)
        self.label_30.setGeometry(QtCore.QRect(120, 80, 47, 13))
        self.label_30.setObjectName("label_30")
        self.openCameraButton = QtWidgets.QPushButton(self.cameraGroupBox)
        self.openCameraButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.openCameraButton.setObjectName("openCameraButton")
        self.closeCameraButton = QtWidgets.QPushButton(self.cameraGroupBox)
        self.closeCameraButton.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.closeCameraButton.setObjectName("closeCameraButton")
        self.calibrateButton = QtWidgets.QPushButton(self.cameraGroupBox)
        self.calibrateButton.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.calibrateButton.setObjectName("calibrateButton")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 141, 80))
        self.groupBox.setObjectName("groupBox")
        self.connectButton = QtWidgets.QPushButton(self.groupBox)
        self.connectButton.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.connectButton.setObjectName("connectButton")
        self.ipLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ipLineEdit.setGeometry(QtCore.QRect(20, 50, 91, 20))
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 20, 120, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.motorOnButton = QtWidgets.QPushButton(self.groupBox_2)
        self.motorOnButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.motorOnButton.setObjectName("motorOnButton")
        self.motorOffButton = QtWidgets.QPushButton(self.groupBox_2)
        self.motorOffButton.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.motorOffButton.setObjectName("motorOffButton")
        self.frameProcessingGroupBox = QtWidgets.QGroupBox(TelecineDialog)
        self.frameProcessingGroupBox.setGeometry(QtCore.QRect(20, 520, 651, 101))
        self.frameProcessingGroupBox.setObjectName("frameProcessingGroupBox")
        self.saveCheckBox = QtWidgets.QCheckBox(self.frameProcessingGroupBox)
        self.saveCheckBox.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.saveCheckBox.setObjectName("saveCheckBox")
        self.chooseDirectoryButton = QtWidgets.QPushButton(self.frameProcessingGroupBox)
        self.chooseDirectoryButton.setGeometry(QtCore.QRect(60, 20, 61, 23))
        self.chooseDirectoryButton.setObjectName("chooseDirectoryButton")
        self.tapeBox = QtWidgets.QSpinBox(self.frameProcessingGroupBox)
        self.tapeBox.setGeometry(QtCore.QRect(180, 20, 51, 22))
        self.tapeBox.setMaximum(99)
        self.tapeBox.setSingleStep(1)
        self.tapeBox.setProperty("value", 1)
        self.tapeBox.setObjectName("tapeBox")
        self.label_27 = QtWidgets.QLabel(self.frameProcessingGroupBox)
        self.label_27.setGeometry(QtCore.QRect(130, 20, 47, 13))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frameProcessingGroupBox)
        self.label_28.setGeometry(QtCore.QRect(240, 20, 47, 13))
        self.label_28.setObjectName("label_28")
        self.clipBox = QtWidgets.QSpinBox(self.frameProcessingGroupBox)
        self.clipBox.setGeometry(QtCore.QRect(270, 20, 51, 22))
        self.clipBox.setMaximum(99)
        self.clipBox.setSingleStep(1)
        self.clipBox.setProperty("value", 1)
        self.clipBox.setObjectName("clipBox")
        self.directoryDisplay = QtWidgets.QLabel(self.frameProcessingGroupBox)
        self.directoryDisplay.setGeometry(QtCore.QRect(60, 50, 371, 21))
        self.directoryDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.directoryDisplay.setText("")
        self.directoryDisplay.setObjectName("directoryDisplay")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frameProcessingGroupBox)
        self.groupBox_12.setGeometry(QtCore.QRect(460, 10, 141, 81))
        self.groupBox_12.setObjectName("groupBox_12")
        self.histosCheckBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.histosCheckBox.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.histosCheckBox.setObjectName("histosCheckBox")
        self.sharpnessCheckBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.sharpnessCheckBox.setGeometry(QtCore.QRect(10, 40, 121, 20))
        self.sharpnessCheckBox.setObjectName("sharpnessCheckBox")
        self.reduceFactorBox = QtWidgets.QSpinBox(self.groupBox_12)
        self.reduceFactorBox.setGeometry(QtCore.QRect(80, 60, 37, 20))
        self.reduceFactorBox.setMinimum(1)
        self.reduceFactorBox.setMaximum(20)
        self.reduceFactorBox.setSingleStep(1)
        self.reduceFactorBox.setProperty("value", 1)
        self.reduceFactorBox.setObjectName("reduceFactorBox")
        self.label_32 = QtWidgets.QLabel(self.groupBox_12)
        self.label_32.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_32.setObjectName("label_32")
        self.setDirectoryButton = QtWidgets.QPushButton(self.frameProcessingGroupBox)
        self.setDirectoryButton.setGeometry(QtCore.QRect(360, 20, 75, 23))
        self.setDirectoryButton.setObjectName("setDirectoryButton")
        self.label_22 = QtWidgets.QLabel(self.frameProcessingGroupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_22.setObjectName("label_22")
        self.messageLabel = QtWidgets.QLabel(TelecineDialog)
        self.messageLabel.setGeometry(QtCore.QRect(10, 1000, 601, 31))
        self.messageLabel.setStyleSheet("font color:\'red\'")
        self.messageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.messageLabel.setText("")
        self.messageLabel.setObjectName("messageLabel")
        self.bracketControlGroupBox = QtWidgets.QGroupBox(TelecineDialog)
        self.bracketControlGroupBox.setGeometry(QtCore.QRect(20, 400, 531, 111))
        self.bracketControlGroupBox.setObjectName("bracketControlGroupBox")
        self.darkCoefficientBox = QtWidgets.QDoubleSpinBox(self.bracketControlGroupBox)
        self.darkCoefficientBox.setGeometry(QtCore.QRect(130, 20, 62, 22))
        self.darkCoefficientBox.setMinimum(0.1)
        self.darkCoefficientBox.setMaximum(1.0)
        self.darkCoefficientBox.setSingleStep(0.1)
        self.darkCoefficientBox.setProperty("value", 1.0)
        self.darkCoefficientBox.setObjectName("darkCoefficientBox")
        self.lightCoefficientBox = QtWidgets.QDoubleSpinBox(self.bracketControlGroupBox)
        self.lightCoefficientBox.setGeometry(QtCore.QRect(280, 20, 62, 22))
        self.lightCoefficientBox.setMinimum(0.1)
        self.lightCoefficientBox.setMaximum(10.0)
        self.lightCoefficientBox.setSingleStep(0.1)
        self.lightCoefficientBox.setProperty("value", 1.0)
        self.lightCoefficientBox.setObjectName("lightCoefficientBox")
        self.label_12 = QtWidgets.QLabel(self.bracketControlGroupBox)
        self.label_12.setGeometry(QtCore.QRect(90, 20, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_21 = QtWidgets.QLabel(self.bracketControlGroupBox)
        self.label_21.setGeometry(QtCore.QRect(230, 20, 47, 13))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.bracketControlGroupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 60, 94, 16))
        self.label_23.setObjectName("label_23")
        self.shutterSpeedWaitBox = QtWidgets.QSpinBox(self.bracketControlGroupBox)
        self.shutterSpeedWaitBox.setGeometry(QtCore.QRect(140, 60, 37, 20))
        self.shutterSpeedWaitBox.setMaximum(10)
        self.shutterSpeedWaitBox.setSingleStep(1)
        self.shutterSpeedWaitBox.setProperty("value", 3)
        self.shutterSpeedWaitBox.setObjectName("shutterSpeedWaitBox")
        self.label_24 = QtWidgets.QLabel(self.bracketControlGroupBox)
        self.label_24.setGeometry(QtCore.QRect(180, 60, 87, 16))
        self.label_24.setObjectName("label_24")
        self.shutterAutoWaitBox = QtWidgets.QSpinBox(self.bracketControlGroupBox)
        self.shutterAutoWaitBox.setGeometry(QtCore.QRect(280, 60, 37, 20))
        self.shutterAutoWaitBox.setMaximum(20)
        self.shutterAutoWaitBox.setSingleStep(1)
        self.shutterAutoWaitBox.setProperty("value", 6)
        self.shutterAutoWaitBox.setObjectName("shutterAutoWaitBox")
        self.label_26 = QtWidgets.QLabel(self.bracketControlGroupBox)
        self.label_26.setGeometry(QtCore.QRect(330, 60, 33, 16))
        self.label_26.setObjectName("label_26")
        self.bracketCheckBox = QtWidgets.QCheckBox(self.bracketControlGroupBox)
        self.bracketCheckBox.setGeometry(QtCore.QRect(20, 20, 70, 17))
        self.bracketCheckBox.setObjectName("bracketCheckBox")
        self.groupBox_11 = QtWidgets.QGroupBox(self.bracketControlGroupBox)
        self.groupBox_11.setGeometry(QtCore.QRect(370, 20, 120, 81))
        self.groupBox_11.setObjectName("groupBox_11")
        self.mergeNoneRadioButton = QtWidgets.QRadioButton(self.groupBox_11)
        self.mergeNoneRadioButton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.mergeNoneRadioButton.setChecked(True)
        self.mergeNoneRadioButton.setObjectName("mergeNoneRadioButton")
        self.mergeMertensRadioButton = QtWidgets.QRadioButton(self.groupBox_11)
        self.mergeMertensRadioButton.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.mergeMertensRadioButton.setObjectName("mergeMertensRadioButton")
        self.mergeDebevecRadioButton = QtWidgets.QRadioButton(self.groupBox_11)
        self.mergeDebevecRadioButton.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.mergeDebevecRadioButton.setObjectName("mergeDebevecRadioButton")
        self.motorSettingsGroupBox = QtWidgets.QGroupBox(TelecineDialog)
        self.motorSettingsGroupBox.setGeometry(QtCore.QRect(20, 630, 631, 81))
        self.motorSettingsGroupBox.setObjectName("motorSettingsGroupBox")
        self.pulleyRatioBox = QtWidgets.QDoubleSpinBox(self.motorSettingsGroupBox)
        self.pulleyRatioBox.setGeometry(QtCore.QRect(130, 50, 62, 22))
        self.pulleyRatioBox.setMinimum(0.25)
        self.pulleyRatioBox.setMaximum(4.0)
        self.pulleyRatioBox.setSingleStep(0.25)
        self.pulleyRatioBox.setProperty("value", 1.0)
        self.pulleyRatioBox.setObjectName("pulleyRatioBox")
        self.label_18 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_18.setObjectName("label_18")
        self.stepsPerRevBox = QtWidgets.QSpinBox(self.motorSettingsGroupBox)
        self.stepsPerRevBox.setGeometry(QtCore.QRect(130, 20, 61, 22))
        self.stepsPerRevBox.setMaximum(12000)
        self.stepsPerRevBox.setSingleStep(200)
        self.stepsPerRevBox.setProperty("value", 200)
        self.stepsPerRevBox.setObjectName("stepsPerRevBox")
        self.label_20 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.label_20.setObjectName("label_20")
        self.label_11 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_11.setGeometry(QtCore.QRect(200, 20, 47, 13))
        self.label_11.setObjectName("label_11")
        self.pulseEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.pulseEdit.setGeometry(QtCore.QRect(310, 20, 31, 16))
        self.pulseEdit.setObjectName("pulseEdit")
        self.dirEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.dirEdit.setGeometry(QtCore.QRect(370, 20, 31, 16))
        self.dirEdit.setObjectName("dirEdit")
        self.label_13 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_13.setGeometry(QtCore.QRect(270, 20, 41, 16))
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_19.setGeometry(QtCore.QRect(350, 20, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_25 = QtWidgets.QLabel(self.motorSettingsGroupBox)
        self.label_25.setGeometry(QtCore.QRect(420, 20, 47, 13))
        self.label_25.setObjectName("label_25")
        self.triggerEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.triggerEdit.setGeometry(QtCore.QRect(470, 20, 31, 16))
        self.triggerEdit.setObjectName("triggerEdit")
        self.setMotorButton = QtWidgets.QPushButton(self.motorSettingsGroupBox)
        self.setMotorButton.setGeometry(QtCore.QRect(510, 20, 75, 23))
        self.setMotorButton.setObjectName("setMotorButton")
        self.enaEdit = QtWidgets.QLineEdit(self.motorSettingsGroupBox)
        self.enaEdit.setGeometry(QtCore.QRect(230, 20, 31, 16))
        self.enaEdit.setObjectName("enaEdit")
        self.enaLevelCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.enaLevelCheckBox.setGeometry(QtCore.QRect(230, 40, 41, 17))
        self.enaLevelCheckBox.setObjectName("enaLevelCheckBox")
        self.pulseLevelCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.pulseLevelCheckBox.setGeometry(QtCore.QRect(310, 40, 41, 17))
        self.pulseLevelCheckBox.setObjectName("pulseLevelCheckBox")
        self.dirLevelCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.dirLevelCheckBox.setGeometry(QtCore.QRect(370, 40, 41, 17))
        self.dirLevelCheckBox.setObjectName("dirLevelCheckBox")
        self.triggerLevelCheckBox = QtWidgets.QCheckBox(self.motorSettingsGroupBox)
        self.triggerLevelCheckBox.setGeometry(QtCore.QRect(470, 40, 41, 17))
        self.triggerLevelCheckBox.setObjectName("triggerLevelCheckBox")

        self.retranslateUi(TelecineDialog)
        self.awbModeBox.setCurrentIndex(1)
        self.exposureModeBox.setCurrentIndex(1)
        self.takeImageButton.clicked.connect(TelecineDialog.takeImage)
        self.captureStopButton.clicked.connect(TelecineDialog.captureStop)
        self.setGainsButton.clicked.connect(TelecineDialog.setGains)
        self.setShutterSpeedButton.clicked.connect(TelecineDialog.setShutterSpeed)
        self.setFrameRateButton.clicked.connect(TelecineDialog.setFrameRate)
        self.autoExposureCheckBox.stateChanged['int'].connect(TelecineDialog.setAutoExposure)
        self.forwardOneButton.clicked.connect(TelecineDialog.forwardOne)
        self.backwardOneButton.clicked.connect(TelecineDialog.backwardOne)
        self.forwardButton.clicked.connect(TelecineDialog.forward)
        self.backwardButton.clicked.connect(TelecineDialog.backward)
        self.motorStopButton.clicked.connect(TelecineDialog.motorStop)
        self.setCorrectionsButton.clicked['bool'].connect(TelecineDialog.setCorrections)
        self.saveCheckBox.stateChanged['int'].connect(TelecineDialog.setSave)
        self.setIsoButton.clicked.connect(TelecineDialog.setIso)
        self.getCameraSettingsButton.clicked.connect(TelecineDialog.getCameraSettings)
        self.chooseDirectoryButton.clicked.connect(TelecineDialog.chooseDirectory)
        self.sharpnessCheckBox.stateChanged['int'].connect(TelecineDialog.setSharpness)
        self.histosCheckBox.stateChanged['int'].connect(TelecineDialog.setHistos)
        self.connectButton.clicked['bool'].connect(TelecineDialog.connectDisconnect)
        self.autoGetSettingsCheckBox.stateChanged['int'].connect(TelecineDialog.setAutoGetSettings)
        self.openCameraButton.clicked.connect(TelecineDialog.openCamera)
        self.setMotorButton.clicked.connect(TelecineDialog.setMotorInitSettings)
        self.captureStartButton.clicked.connect(TelecineDialog.captureStart)
        self.setDirectoryButton.clicked.connect(TelecineDialog.setDirectory)
        self.mergeNoneRadioButton.toggled['bool'].connect(TelecineDialog.setMerge)
        self.mergeMertensRadioButton.toggled['bool'].connect(TelecineDialog.setMerge)
        self.mergeDebevecRadioButton.toggled['bool'].connect(TelecineDialog.setMerge)
        self.closeCameraButton.clicked.connect(TelecineDialog.closeCamera)
        self.reduceFactorBox.valueChanged['int'].connect(TelecineDialog.setReduce)
        self.calibrateButton.clicked.connect(TelecineDialog.calibrate)
        self.motorOnButton.clicked.connect(TelecineDialog.motorOn)
        self.motorOffButton.clicked.connect(TelecineDialog.motorOff)
        QtCore.QMetaObject.connectSlotsByName(TelecineDialog)

    def retranslateUi(self, TelecineDialog):
        _translate = QtCore.QCoreApplication.translate
        TelecineDialog.setWindowTitle(_translate("TelecineDialog", "CamDialog"))
        self.cameraSettingsGroupBox.setTitle(_translate("TelecineDialog", "Camera settings"))
        self.label.setText(_translate("TelecineDialog", "Color"))
        self.awbModeBox.setItemText(4, _translate("TelecineDialog", "shade"))
        self.awbModeBox.setItemText(5, _translate("TelecineDialog", "tungsten"))
        self.awbModeBox.setItemText(6, _translate("TelecineDialog", "fluorescent"))
        self.awbModeBox.setItemText(7, _translate("TelecineDialog", "incandescent"))
        self.awbModeBox.setItemText(8, _translate("TelecineDialog", "flash"))
        self.awbModeBox.setItemText(9, _translate("TelecineDialog", "horizon"))
        self.setGainsButton.setText(_translate("TelecineDialog", "Set"))
        self.label_2.setText(_translate("TelecineDialog", "Shutter"))
        self.setShutterSpeedButton.setText(_translate("TelecineDialog", "Set"))
        self.setFrameRateButton.setText(_translate("TelecineDialog", "Set"))
        self.autoExposureCheckBox.setText(_translate("TelecineDialog", "Auto"))
        self.label_4.setText(_translate("TelecineDialog", "Gains"))
        self.label_7.setText(_translate("TelecineDialog", "Digital"))
        self.label_8.setText(_translate("TelecineDialog", "Analog"))
        self.exposureModeBox.setCurrentText(_translate("TelecineDialog", "auto"))
        self.exposureModeBox.setItemText(1, _translate("TelecineDialog", "auto"))
        self.label_5.setText(_translate("TelecineDialog", "Brightness"))
        self.label_6.setText(_translate("TelecineDialog", "Contrast"))
        self.autoGetSettingsCheckBox.setText(_translate("TelecineDialog", "AutoGet"))
        self.setCorrectionsButton.setText(_translate("TelecineDialog", "Set"))
        self.label_10.setText(_translate("TelecineDialog", "Saturation"))
        self.label_14.setText(_translate("TelecineDialog", "Iso"))
        self.setIsoButton.setText(_translate("TelecineDialog", "Set"))
        self.label_15.setText(_translate("TelecineDialog", "compensation"))
        self.getCameraSettingsButton.setText(_translate("TelecineDialog", "Get Settings"))
        self.cameraControlGroupBox.setTitle(_translate("TelecineDialog", "Camera control"))
        self.takeImageButton.setText(_translate("TelecineDialog", "Shot"))
        self.captureStopButton.setText(_translate("TelecineDialog", "Stop"))
        self.captureStartButton.setText(_translate("TelecineDialog", "Capture"))
        self.groupBox_5.setTitle(_translate("TelecineDialog", "Capture parameters"))
        self.playButton.setText(_translate("TelecineDialog", "Preview"))
        self.onFrameButton.setText(_translate("TelecineDialog", "OnFrame"))
        self.onTriggerButton.setText(_translate("TelecineDialog", "OnTrigger"))
        self.label_3.setText(_translate("TelecineDialog", "Framerate"))
        self.label_31.setText(_translate("TelecineDialog", "Framerate"))
        self.label_29.setText(_translate("TelecineDialog", "Motor speed"))
        self.motorControlGroupBox.setTitle(_translate("TelecineDialog", "Motor control"))
        self.forwardButton.setText(_translate("TelecineDialog", "Fwd"))
        self.backwardButton.setText(_translate("TelecineDialog", "Bck"))
        self.motorStopButton.setText(_translate("TelecineDialog", "Stop"))
        self.forwardOneButton.setText(_translate("TelecineDialog", "FwdOne"))
        self.backwardOneButton.setText(_translate("TelecineDialog", "BwkOne"))
        self.label_17.setText(_translate("TelecineDialog", "Speed"))
        self.groupBox_7.setTitle(_translate("TelecineDialog", "Initialization"))
        self.cameraGroupBox.setTitle(_translate("TelecineDialog", "Camera"))
        self.label_16.setText(_translate("TelecineDialog", "Mode"))
        self.useCalibrationCheckBox.setText(_translate("TelecineDialog", "Use calibration"))
        self.label_9.setText(_translate("TelecineDialog", "Hres"))
        self.label_30.setText(_translate("TelecineDialog", "Vres"))
        self.openCameraButton.setText(_translate("TelecineDialog", "Open"))
        self.closeCameraButton.setText(_translate("TelecineDialog", "Close"))
        self.calibrateButton.setText(_translate("TelecineDialog", "Calibrate"))
        self.groupBox.setTitle(_translate("TelecineDialog", "Raspberry"))
        self.connectButton.setText(_translate("TelecineDialog", "Connect"))
        self.ipLineEdit.setText(_translate("TelecineDialog", "192.168.0.22"))
        self.groupBox_2.setTitle(_translate("TelecineDialog", "Motor"))
        self.motorOnButton.setText(_translate("TelecineDialog", "On"))
        self.motorOffButton.setText(_translate("TelecineDialog", "Off"))
        self.frameProcessingGroupBox.setTitle(_translate("TelecineDialog", "Frame processing"))
        self.saveCheckBox.setText(_translate("TelecineDialog", "Save"))
        self.chooseDirectoryButton.setText(_translate("TelecineDialog", "Directory"))
        self.label_27.setText(_translate("TelecineDialog", "Tape"))
        self.label_28.setText(_translate("TelecineDialog", "Clip"))
        self.groupBox_12.setTitle(_translate("TelecineDialog", "Display"))
        self.histosCheckBox.setText(_translate("TelecineDialog", "Histos"))
        self.sharpnessCheckBox.setText(_translate("TelecineDialog", "Sharpness"))
        self.label_32.setText(_translate("TelecineDialog", "Reduce by "))
        self.setDirectoryButton.setText(_translate("TelecineDialog", "Set"))
        self.label_22.setText(_translate("TelecineDialog", "To"))
        self.bracketControlGroupBox.setTitle(_translate("TelecineDialog", "Bracket control"))
        self.label_12.setText(_translate("TelecineDialog", "Dark"))
        self.label_21.setText(_translate("TelecineDialog", "Light"))
        self.label_23.setText(_translate("TelecineDialog", "Shutter speed wait "))
        self.label_24.setText(_translate("TelecineDialog", "Shutter auto wait "))
        self.label_26.setText(_translate("TelecineDialog", "frames"))
        self.bracketCheckBox.setText(_translate("TelecineDialog", "Bracket "))
        self.groupBox_11.setTitle(_translate("TelecineDialog", "Merge method"))
        self.mergeNoneRadioButton.setText(_translate("TelecineDialog", "None"))
        self.mergeMertensRadioButton.setText(_translate("TelecineDialog", "Mertens"))
        self.mergeDebevecRadioButton.setText(_translate("TelecineDialog", "Debevec"))
        self.motorSettingsGroupBox.setTitle(_translate("TelecineDialog", "Motor settings"))
        self.label_18.setText(_translate("TelecineDialog", "Steps per Rev"))
        self.label_20.setText(_translate("TelecineDialog", "Frame/Motor ratio"))
        self.label_11.setText(_translate("TelecineDialog", "ON"))
        self.label_13.setText(_translate("TelecineDialog", "PULSE"))
        self.label_19.setText(_translate("TelecineDialog", "DIR"))
        self.label_25.setText(_translate("TelecineDialog", "TRIGGER"))
        self.setMotorButton.setText(_translate("TelecineDialog", "Set"))
        self.enaLevelCheckBox.setText(_translate("TelecineDialog", "High"))
        self.pulseLevelCheckBox.setText(_translate("TelecineDialog", "High"))
        self.dirLevelCheckBox.setText(_translate("TelecineDialog", "High"))
        self.triggerLevelCheckBox.setText(_translate("TelecineDialog", "High"))

